model:
  metric:
    class_path: internal.metrics.inverse_depth_metrics.HasInverseDepthMetrics
    init_args:
      depth_loss_type: l2
  renderer: internal.renderers.gsplat_renderer.GSPlatRenderer
  renderer_output_types:
    - rgb
    - inverse_depth
data:
  parser: internal.dataparsers.estimated_depth_colmap_dataparser.EstimatedDepthColmap
cache_all_images: true