max_steps: 60_000
data:
  train_max_num_images_to_cache: 4096  # avoid OOM
  parser:
    class_path: MatrixCity
    init_args:
      train:
        - aerial/block_1/transforms_origin.json
        - street/small_city_road_down/transforms-0_59.json
      test:
        - aerial/block_1_test/transforms_origin.json
        - street/small_city_road_down_test/transforms-0_2.json
      scale: 0.1  # default is 0.01, remember to rescale `spatial_lr_scale` below by the same factor if you changed this
      depth_read_step: 4
model:
  gaussian:
    optimization:
      spatial_lr_scale: 2  # avoid large xyz learning rate
    sh_degree: 0  # avoid CUDA OOM
  density:
    densify_grad_threshold: 0.0006  # avoid CUDA OOM
    densify_until_iter: 30_000
  renderer: internal.renderers.gsplat_renderer.GSPlatRenderer